# Generated by Django 5.0.6 on 2024-06-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='Curr_ID',
            new_name='Cur_ID',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='Cur_name',
            new_name='Cur_Name',
        ),
    ]
